#!/usr/bin/env bash
apt-get -y update

packets=(
	amd64-microcode
	apt-get
	aptitude
	at
	bash-completion
	bc
	beep
	ccrypt
	coreutils
	curl
	dconf-tools
	debsums
	dkms
	dnsutils
	dos2unix
	dosfstools
	dpkg
	eject
	ethtool
	exfat-fuse
	exfat-utils
	fail2ban
	flac
	g++
	gcc
	gdisk
	git
	gksu
	gpart
	gparted
	hal-info
	hashalot
	hexedit
	htop
	hwinfo
	intel-microcode
	libnss-winbind
	links
	lshw
	mailutils
	make
	mc
	mintupdate
	mtr
	ncurses-bin
	netcat
	ntfs-3g
	openssh-server
	openssl
	p7zip-full
	parallel
	pciutils
	perl
	powertop
	printer-driver-splix
	procinfo
	putty
	pv
	pwgen
	python2
	python3
	rcconf
	rpm
	rsync
	samba
	screen
	scrub
	secure-delete
	shellcheck
	smartmontools
	smbclient
	speedtest-cli
	ssh
	sshpass
	strace
	swaks
	synaptic
	telnet
	testdisk
	tightvncserver
	traceroute
	udisks
	udisks2
	ufw
	unrar
	unzip
	util-linux
	vsftpd
	wget
	whoami
	winbind
	zerofree
	zip
)

apt-get purge -y cups

for packet in ${packets[*]}
do
	apt-get install -y "$packet"
done

apt-get clean
apt-get -y autoclean
apt-get -y autoremove

sync
