#!/usr/bin/env bash
apt-get -y update

packets=(
	apache2
	docker-ce
	docker.io
	mailutils
	mysql-server
	openssl
	php7.4
	php7.4-gd
	php7.4-mbstring
	php7.4-mysql
	php7.4-xml
	postfix
	samba
	ssh
	sshd
)

for packet in ${packets[*]}
do
	apt-get install -y "$packet"
done

apt purge cups

apt-get clean
apt-get -y autoclean
apt-get -y autoremove

sync
