#!/usr/bin/env bash
echo === WRITE 1GiB ===
echo -n "sync..." ; sync ; echo "ok"
echo 3 > /proc/sys/vm/drop_caches
time {
	dd if=/dev/zero of=./temp bs=1M count=1k conv=fdatasync status=progress oflag=direct
	echo -n "sync..." ; sync ; echo "ok"
}
rm -f ./temp
echo -n "sync..." ; sync ; echo "ok"
echo Done.
