#!/usr/bin/env bash
echo === WRITE 1GiB ===
sync
echo 3 > /proc/sys/vm/drop_caches
time {
	dd if=/dev/zero of=./temp bs=1048576 count=1024 conv=fdatasync status=progress oflag=direct
	sync
}
rm -f ./temp
sync
echo Done.
