#!/usr/bin/env bash
apt-get -y update
apt-get -y upgrade
apt-get -y dist-upgrade
apt-get -f -y install
apt-get -y clean
apt-get -y autoclean
apt-get -y autoremove
echo -n "sync..." ; sync ; echo "ok"
