#!/usr/bin/env bash
echo -n "sync..." ; sync ; echo "ok"
df -HB MiB .
pv -B 1M < /dev/zero >> "zeros.tmp"
echo -n "sync..." ; sync ; echo "ok"
pv -B 512 < /dev/zero >> "zeros.tmp"
sync
df -HB 1 .
echo -n cleaning...
rm zeros.tmp
echo ok
echo -n "sync..." ; sync ; echo "ok"
df -HB MiB .
